import {Runtime,RuntimeError} from './runtime.js';import {get,put} from './storage.js';import {makeEvent,appendEvent} from './sync.js';
const root=document.querySelector('#app');let rt=new Runtime();let err='';
function render(){const s=rt.s;root.innerHTML=`<div class="shell"><div class="top"><div><div class="eyebrow">NEXUS VFX EYE · 3.9</div><h1>Production Runtime</h1></div><span class="pill">${s.state}</span></div>${err?`<div class="card error">${esc(err)}</div>`:''}${view(s)}</div>`;wire();}
function view(s){if(s.state==='BOOT')return card('Boot','Initialize the local runtime.',[['BOOT_COMPLETE','Enter NEXUS']]);if(s.state==='HOME')return card('Day 001','Reading the Plate · Runtime training slice.',[['OPEN_DAY','Open Day'],['OPEN_SKILL_GRAPH','Skill Graph'],['OPEN_REVIEW_QUEUE','Review Queue']]);if(s.state==='DAY_OVERVIEW')return card('Day 001','Stage -1 is mandatory before Mission.',[['START_STAGE_MINUS_1','Start Stage -1']]);if(s.state==='STAGE_MINUS_1')return card('PRE-SHOT MASTERCLASS','Complete the masterclass before Stage 0.',[['OPEN_STAGE_0','Continue to Stage 0']]);if(s.state==='STAGE_0_CONSENT')return card('ZERO STAGE','Image generation/reveal requires explicit consent.',[['GRANT_STAGE_0_CONSENT','I consent'],['DENY_STAGE_0_CONSENT','Not now']]);if(s.state==='MISSION_INTRO')return card('Mission Intro','Consent recorded. Continue to the practice mission.',[['START_MISSION','Start Mission']]);if(s.state==='MISSION_PLAY')return mission();if(s.state==='EXAMINER_REVIEW')return card('Examiner Review','Attempt accepted by runtime. Deterministic examiner may now score it.',[['OPEN_RESULTS','View Results']]);if(s.state==='RESULTS')return card('Results','Mastery is derived; this client cannot write it.',[['OPEN_SKILL_GRAPH','Skill Graph'],['RESET_SAFE','Return Home']]);return card(s.state,'Runtime surface ready.',[['RESET_SAFE','Home']]);}
function card(title,body,buttons){return `<section class="card"><h2>${title}</h2><p>${body}</p>${buttons.map(([a,t])=>`<button data-action="${a}">${t}</button>`).join('')}</section>`;}
function mission(){const a=rt.s.attempt;return `<section class="card"><h2>Blind Diagnostic</h2><label>Observations<textarea id="obs">${esc(JSON.stringify(a.observations||[]))}</textarea></label><label>Diagnosis<input id="diag" value="${esc(a.diagnosis||'')}" placeholder="Primary diagnosis"></label><label>Causal chain<input id="cause" value="${esc(a.causal_chain||'')}" placeholder="Cause → mechanism → symptom"></label><label>Correction order<input id="corr" value="${esc(a.correction_order||'')}" placeholder="Upstream → downstream"></label><label>Confidence 0–100<input id="conf" type="number" min="0" max="100" value="${a.confidence??''}"></label><button data-save="1">Save Fields</button><button data-hyp="1" class="secondary">Add Hypothesis</button><button data-evidence="1" class="secondary">Add Evidence</button><div>${(a.hypotheses||[]).map(x=>`<span class="pill">H: ${esc(String(x))}</span>`).join('')}</div><div>${(a.evidence||[]).map(x=>`<span class="pill">E: ${esc(String(x))}</span>`).join('')}</div><button data-action="SUBMIT_ATTEMPT">Submit for Examiner</button></section>`;}
function esc(x){return String(x).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');}
function wire(){document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));document.querySelector('[data-save]')?.addEventListener('click',save);document.querySelector('[data-hyp]')?.addEventListener('click',()=>{const x=prompt('Competing hypothesis');if(x)act('ADD_HYPOTHESIS',{value:x});});document.querySelector('[data-evidence]')?.addEventListener('click',()=>{const x=prompt('Evidence anchor (frame/region/metric)');if(x)act('ADD_EVIDENCE',{value:x});});}
async function save(){try{act('SET_OBSERVATION',{value:JSON.parse(document.querySelector('#obs').value||'[]')});act('SET_DIAGNOSIS',{value:document.querySelector('#diag').value});act('SET_CAUSAL_CHAIN',{value:document.querySelector('#cause').value});act('SET_CORRECTION_ORDER',{value:document.querySelector('#corr').value});act('SET_CONFIDENCE',{value:Number(document.querySelector('#conf').value)});const e=await makeEvent('ATTEMPT_STATE',rt.snapshot());await appendEvent(e);await put('runtime',{id:'current',snapshot:rt.snapshot()});err='';render();}catch(e){err=e.message;render();}}
async function act(action,p={}){try{rt.dispatch(action,action==='OPEN_DAY'?{day_id:'DAY-001',mission_id:'MISSION-DAY-001'}:p);await put('runtime',{id:'current',snapshot:rt.snapshot()});err='';render();}catch(e){err=e instanceof RuntimeError?e.message:String(e);render();}}
(async()=>{const saved=await get('runtime','current');if(saved)rt=new Runtime(saved.snapshot);else{rt.dispatch('BOOT_COMPLETE');await put('runtime',{id:'current',snapshot:rt.snapshot()});}if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();})();